General:
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  gnss_ephem_topic: "/ublox_driver/ephem"
  gnss_glo_ephem_topic: "/ublox_driver/glo_ephem"
  gnss_meas_topic: "/ublox_driver/range_meas"
  gnss_iono_params_topic: "/ublox_driver/iono_params"
  navsatfix_topic: "/ublox_driver/receiver_lla"
  receiver_pvt_topic: "/ublox_driver/receiver_pvt"
  GNSS_enable: 1
  save_path: "/home/garronliu/save_datas/"
  previous_map: ""
  bagname: "mid360_init"
  lidar_type: 0
  blind: 0.5 # 0.5
  point_filter_num: 3
  extrinsic_tran: [-0.011, -0.02329, 0.04412]
  extrinsic_rota: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
  is_save_map: 0

Odometry:
  max_init: 30
  cov_gyr: 0.1
  cov_acc: 1
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  # down_size: 0.5
  down_size: 0.1
  dept_err: 0.02
  beam_err: 0.05
  # voxel_size: 4
  voxel_size: 1
  min_eigen_value: 0.0025
  degrade_bound: 10
  point_notime: 0

LocalBA:
  win_size: 10
  max_layer: 2
  cov_gyr: 0.01
  cov_acc: 2
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  min_ba_point: 1
  plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
  imu_coef: 0.0002
  thread_num: 5

GNSS:
  imu_gnss_only_enable: false
  max_delay: 0.05 #不应该超过lidar扫描周期的一半，否则可能会匹配到错误的PVT
  gnss_local_time_diff: 18.0
  pvt_hacc_thres: 1.0
  pvt_vacc_thres: 2.0
  pvt_velacc_thres: 1.0
  pvt_min_position_std: 0.05
  pvt_min_velocity_std: 0.05
  pvt_iekf_max_iter: 3
  pvt_iekf_converge_pos: 0.001
  pvt_iekf_converge_vel: 0.001
  psr_std_thres: 2.0
  dopp_std_thres: 2.0
  elevation_thres: 30.0
  track_num_thres: 20
  min_obs: 10
  min_frames: 10
  min_hor_vel: 0.3
  navsatfix_compare_enable: 0

Loop:
  jud_default: 0.45
  icp_eigval: 9
  ratio_drift: 0.01

GBA:
  voxel_size: 2
  min_eigen_value: 0.01
  eigen_value_array: [4.0, 4.0, 4.0, 4.0]
  total_max_iter: 6
